services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webapp-blue
      - webapp-green

  webapp-blue:
    image: ${DOCKER_USERNAME}/student-info-app:latest
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  webapp-green:
    image: ${DOCKER_USERNAME}/student-info-app:latest
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

volumes:
  sqlserver_data:
