name: Deploy Blue/Green

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Clean up orphan containers
        run: docker-compose down --remove-orphans || true
      
      - name: Determine target environment
        id: target
        run: |
          if grep -q "webapp-blue:80" nginx.conf; then
            echo "target=green" >> $GITHUB_OUTPUT
            echo "current=blue" >> $GITHUB_OUTPUT
            echo "Current: Blue, Deploying to: Green"
          else
            echo "target=blue" >> $GITHUB_OUTPUT
            echo "current=green" >> $GITHUB_OUTPUT
            echo "Current: Green, Deploying to: Blue"
          fi
      
      - name: Deploy to inactive environment
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker-compose pull webapp-${{ steps.target.outputs.target }}
          docker-compose up -d webapp-${{ steps.target.outputs.target }}
          sleep 30
      
      - name: Health check
        run: |
          if [ "${{ steps.target.outputs.target }}" = "blue" ]; then
            docker-compose exec -T webapp-blue curl -f http://localhost:80 || exit 1
          else
            docker-compose exec -T webapp-green curl -f http://localhost:80 || exit 1
          fi
          echo "Health check passed!"
      
      - name: Switch traffic
        run: |
          echo "Switching to ${{ steps.target.outputs.target }} environment..."
          cp nginx-${{ steps.target.outputs.target }}.conf nginx.conf
          docker-compose restart nginx
          echo "Traffic switched to ${{ steps.target.outputs.target }}!"
      
      - name: Verify deployment
        run: |
          sleep 5
          curl -f http://localhost:3000 || exit 1
          echo "Deployment successful!"
          echo "Active environment: ${{ steps.target.outputs.target }}"
          echo "Standby environment: ${{ steps.target.outputs.current }}"
